### ISSUE TITLE
 C2-13242-2 error while trying to download VPK

### ISSUE THREAD

**Issue by Cimmerian-Iter** [SKGleba/iTLS-Enso#1]
Users report a  C2-13242-2 error code while trying to download vpk from websites like GitHub or brewology. Error reported on 3.65 and 3.60 1st with download enabler through browser and 2nd with the qr code reader, with or without dns. Is it a known bug?
Installed compat modules and updates certs.

**Comment by SKGleba** [comment]
Works fine here on 3.50, 3.60, 3.65, 3.67.
The problem is on your side.
