### ISSUE TITLE
Every time I install iTLS my NoNpDrm plugin file changed some way

### ISSUE THREAD

**Issue by t33st33r** [SKGleba/iTLS-Enso#10]
What is nonpdrm_un.skprx?
When I install your software I see no more my ur0:/tai/nonpdrm.skprx file.
There is a bigger nonpdrm_un.skprx in the same place of the original.
I am using CFWv3.60 and I have this issue no matter what base nonpdrm is v1.1 or v1.2

Please... excuse my low level english language. This is not my native language.
___
[nonpdrm_un.skprx.gz](https://github.com/SKGleba/iTLS-Enso/files/3968564/nonpdrm_un.skprx.gz)

**Comment by SKGleba** [comment]
The official installer does not modify other plugins in any way
