### ISSUE TITLE
FW 3.60 Problem with web-browser app

### ISSUE THREAD

**Issue by Blackshadow514** [SKGleba/iTLS-Enso#13]
Hello, I installed the full package of the plugin but after following the instructions and after reboot ps vita my web browser app doesn't open. I mean if I try to open the web browser app, it automatically put me in the home screen. What can I do?

**Comment by SKGleba** [comment]
Whats your current firmware?

**Comment by Blackshadow514** [comment]
my firmware is 3.60. I've seen your message now... sorry.
I even installed "ioplus" plugin because some people had issues without it, but nothing changed.

**Comment by SKGleba** [comment]
Ok, is there an error code?

**Comment by Blackshadow514** [comment]
no, the app just automatically brings me to the home screen but it stays in the background(like when you open an app and then press the Ps button on the bottom left side with PlayStation logo to go back on the home screen). The same thing happens if I try to go on a recent web page which I surf on the internet with the browser. Thx for your openness.

**Comment by SKGleba** [comment]
Try installing selectively, and the latest version.
