### ISSUE TITLE
Version check up

### ISSUE THREAD

**Issue by Mapachillo** [SKGleba/iTLS-Enso#16]
I had the previous versions and when I updated to the newest one, I don't remember If I uninstalled everything before the update. Is there a way to check that?
Also I noticed I cannot access the twitter vita application since the update

**Comment by SKGleba** [comment]
If the full package is installed you should have itls.skprx in ur0:tai, two *.skpr0 files in vs0:/sys/external/ and ScePsp2Compat.supr0 in vs0:/data/external/webcore/
