### ISSUE TITLE
Is that an unnecessary remove?

### ISSUE THREAD

**Issue by aon3ko** [SKGleba/iTLS-Enso#17]
https://github.com/SKGleba/iTLS-Enso/blob/4d8529c8c83b646c8f6c7647aa974a6f6997e9a6/main.c#L141
I see before it there is a ```sceIoRename```. If my understand is correct, it will rename ```CA_LIST.cer_old``` to ```CA_LIST.cer```, and ```CA_LIST.cer_old``` will disappear.

**Comment by SKGleba** [comment]
If the rename fails for some reason - remove the cer_old.
But yeah, its pointless, i will remove it in the next release.
