### ISSUE TITLE
Freezes at health warning and requires a reboot

### ISSUE THREAD

**Issue by HELLOcommaWORLD** [SKGleba/iTLS-Enso#18]
PS Vita 3.65 Enso.

That started happening after I installed this utility.

**Comment by SKGleba** [comment]
- Do you have autoplugin?
- What are your installed plugins?
Also please ask on reddit.com/r/vitahacks, reopen the issue if you find an incompatibility.

**Comment by HELLOcommaWORLD** [comment]
For some reason, I turned on the Vita and it didn't freeze. Did that a few times just to double check.

Thank you and sorry for bothering.
