### ISSUE TITLE
Brick Causing apps

### ISSUE THREAD

**Issue by Honeylife77** [SKGleba/iTLS-Enso#19]
My vita is 3.65 ENSO and have iTLS Ensp 3.0

when i  using web browser c2-14900-4 SSL error found

so i try browser-only patch and reboot my vita

after my vita is brick  c1-2738-0

It's a problematic app
It's a serious error.

**Comment by HELLOcommaWORLD** [comment]
The latest release is **3.1.1**
So, why did you use **3.0**??
