### ISSUE TITLE
[3.60 Enso] iTLS compat module (web-browser) breaks Javascript in the web browser

### ISSUE THREAD

**Issue by NinjaWeedle** [SKGleba/iTLS-Enso#20]
When the iTLS compat module (web-browser) is enabled, I am unable to sign into Youtube or any other google service as the website states that Javascript is disabled. '
- Enabling and disabling Javascript in the browser's settings does nothing. 
- Javascript works as normal after the iTLS compat module (web-browser) is uninstalled, and breaks again after reinstalling.

Anyone else have this issue?

**Comment by SKGleba** [comment]
Could not replicate
