### ISSUE TITLE
config.txt reset when uninstalling

### ISSUE THREAD

**Issue by ghost** [SKGleba/iTLS-Enso#21]
when removing the plugin config.txt gets replaced with the backup made when installing, but does not create a backup when uninstalling
someone who uses a sd2vita instead of a memory card may lose access to things like vitashell if they screw something up and need to uninstall and had installed the plugin before the sd2vita plugin

a short loop to locate and remove the necessary lines from the config instead of replacing with an old backup could fix this

**Comment by SKGleba** [comment]
Will be fixed in the next update
