### ISSUE TITLE
Not working on both 3.60, and 3.65

### ISSUE THREAD

**Issue by sevenpastzeero** [SKGleba/iTLS-Enso#23]
Sorry to open a new issue, but I have been trying for the past day with no luck.
iTLS 3.2 is not working on either 3.60 nor 3.65. I have tried multiple installation combos (Full package, plugin only, web browser, update CA, etc) but nothing, Can't access https site on Browser, nor PS store. I can get into PlayStation Network in settings. Trophies did not sync on 3.65, but do sync on 3.60. 
I tried clean installs. No other plugins.
here are my errors:
![2021-06-21-014536](https://user-images.githubusercontent.com/34801304/122691022-af3c5b00-d235-11eb-97f5-d55c56629b28.jpg)
![2021-06-21-014446](https://user-images.githubusercontent.com/34801304/122691029-b6636900-d235-11eb-8ef6-af59bf511083.jpg)

Any help is appreciated.

**Comment by Masamune3210** [comment]
Any particular reason you are in airplane mode?

**Comment by SKGleba** [comment]
check if the itls plugin is in ur0:tai/itls.skprx and has a line in ur0:tai/config.txt.
- make sure that there is no ux0:tai or vs0:tai

**Comment by sevenpastzeero** [comment]
> 
> 
> check if the itls plugin is in ur0:tai/itls.skprx and has a line in ur0:tai/config.txt.
> 
>     * make sure that there is no ux0:tai or vs0:tai

Finally... Deleting ux0:tai folder made it work (which is not very practical since a lot of plugins were already setup there). Then I tried adding 'ur0:tai/itls.skprx' to ux0 config.txt, and rebooted, and everything worked fine.

**Comment by CatKasha** [comment]
> Finally... Deleting ux0:tai folder made it work (which is not very practical since a lot of plugins were already setup there). Then I tried adding 'ur0:tai/itls.skprx' to ux0 config.txt, and rebooted, and everything worked fine.

Better to move plugins that you have in ux0:tai folder to ur0:tai folder and use ur0:tai/config.txt, not ux0:tai/config.txt

**Comment by sevenpastzeero** [comment]
> 
> 
> > Finally... Deleting ux0:tai folder made it work (which is not very practical since a lot of plugins were already setup there). Then I tried adding 'ur0:tai/itls.skprx' to ux0 config.txt, and rebooted, and everything worked fine.
> 
> Better to move plugins that you have in ux0:tai folder to ur0:tai folder and use ur0:tai/config.txt, not ux0:tai/config.txt

Thank you. I just migrated my plugins as you suggested. Everything is working smooth.

**Comment by SNMetamorph** [comment]
> check if the itls plugin is in ur0:tai/itls.skprx and has a line in ur0:tai/config.txt.
> 
>     * make sure that there is no ux0:tai or vs0:tai

May be add this info to README.md? I faced with same problem but found a solution in Issues. But most of users won't do this I guess.
