### ISSUE TITLE
Browser crashes on launch. No error code given.

### ISSUE THREAD

**Issue by Warpshock** [SKGleba/iTLS-Enso#24]
I'm using firmware version 3.60. Browser works as expected without iTLS-Enso (loads http pages. SSL errors on https pages.) When I install the iTLS-Enso the browser crashes immediately when it loads no matter what page is launched. No error is generated. 
I have tried removing and reinstalling with and without other plugins and I have tried the version available from Autoplugin and the VPK from Github.
I have tried clearing cookies.

**Comment by SKGleba** [comment]
reboot
