### ISSUE TITLE
Impossible to install/update HENkaku if iTLS-Enso is enabled

### ISSUE THREAD

**Issue by MayanKoyote** [SKGleba/iTLS-Enso#26]
PS Vita (PCH-1000), FW 3.60, HENkaku Ensō 1.1
Installed iTLS-Enso v3.2
If to try to install HENkaku from henkaku.xyz (i originally wanted to upgrade HENkaku from Release 10 to Release 11)
browser gives constant errors C2-12828-1.
It doesn't matter which site to visit - https://henkaku.xyz or http://henkaku.xyz
Deleting cookies and rebooting doesn't help.
But if to remove (comment out) strings related to itls.skprx in config.txt (and reboot device) - installation process goes without problem.

**Comment by ghost** [comment]
Try #23?

**Comment by MayanKoyote** [comment]
Just curious: this was only my local case and no one else observe something similar?
Regarding the previous comment - of course I didn't have ux0:tai or vs0:tai. Only ur0:tai
