### ISSUE TITLE
My app still doesn't work with TLS 1.2

### ISSUE THREAD

**Issue by blastrock** [SKGleba/iTLS-Enso#3]
Hi,

I am trying to get TLS 1.2 to work in pkgj. From what I understand, it should work out of the box, but somehow it doesn't. My browser does support it thanks to iTLS-Enso, but pkgj still only supports 1.1.

Could you help me understand what I am doing wrong?

I tried messing with the loading order of the modules: https://github.com/blastrock/pkgj/blob/1fc37a948c15039ac8ef18bb8ed006773d9656f5/src/vita.cpp#L440
I compared my HTTP code to samples: https://github.com/blastrock/pkgj/blob/1fc37a948c15039ac8ef18bb8ed006773d9656f5/src/vitahttp.cpp#L64

Do you have an idea what's wrong? Or know of an open source app that works and that I can read to see how I am doing things differently?

**Comment by SKGleba** [comment]
Do you still have this problem or you fixed it?

**Comment by blastrock** [comment]
I still have this issue, with itls-enso 2.0

**Comment by SKGleba** [comment]
I will work on it today

**Comment by Nio9345** [comment]
I also have the same problem. I tried the module and the plugin+ioplus and I still get connection error on apps like VHBB and the browser can't even display the Google page. I have SD2Vita, PSvita Cheat, nonpdrm installed so I don't know if that is the reason.

**Comment by SKGleba** [comment]
Use the web module.
InApp probably will NOT be added.
