### ISSUE TITLE
Does not work with Download Enabler

### ISSUE THREAD

**Issue by TheRadziu** [SKGleba/iTLS-Enso#4]
Scenario 1: 
3.65 console + Download Enabler + HTTP website + Download unsupported filetype = Success, file gets downloaded

Scenario 2:
3.65 console + Download Enabler + iTLS-Enso + HTTPS website + Download unsupported filetype = Fails with SSL Error [NW-8942-3]

Scenario 3:
3.68 console + Download enabler + HTTPS website + Download unsupported filetype = Success, file gets downloaded

**Comment by eth-man** [comment]
At 3.65 got the same issue: Can access ssl but cant download
looks like itls 2.0 works only when compact module installed

**Comment by SKGleba** [comment]
Yea looks like the plugin version got problems with download_enabler, i will look into it

**Comment by Andiweli** [comment]
Same problem here...
PS Vita Slim, Enso Ex 3.65, latest download_enabler - but instead of downloading the file it will be shown in plain text in the browser.

Was working with 3.68 and 3.69 and h-encore.

**Comment by Madridi7** [comment]
I noticed this was closed. But it was never fixed was it?

**Comment by linuxct** [comment]
Yeah, still experiencing this issue over here... Sad

**Comment by SKGleba** [comment]
Why tf did i close this.
Anyways, ill check if the same happens with v3.1

**Comment by SKGleba** [comment]
Ok, so the fix is to have the inapp patch installed too.

**Comment by dface33** [comment]
> Ok, so the fix is to have the inapp patch installed too.

I am having this same problem. What is this inapp patch?
