### ISSUE TITLE
No VPKs

### ISSUE THREAD

**Issue by bamhm182** [SKGleba/iTLS-Enso#8]
I went to download the VPK from the releases tab, but there is only source code. Where can I get the VPK? Thanks!

**Comment by piwi93** [comment]
Same here, I tried using make command and no luck.

Edit: I could find the vpk in vitadb

**Comment by oldskool978** [comment]
Assistance with compilation would be much appreciated.

**Comment by SKGleba** [comment]
New ver:-:
