### ISSUE TITLE
C1-6703-6 at boot

### ISSUE THREAD

**Issue by SKGleba** [SKGleba/iTLS-Enso#9]
### Why does it happen? 
 - [<v3.0]: enso is not running.
 - [v3.0] (decrypted): firmware was reinstalled without clearing the config.
### How to fix?
 - [<v3.0]: reinstall the firmware
 - [v3.0] (decrypted): hold LT at boot and uninstall iTLS via the installer.
### Should NOT happen on 3.1+

**Comment by teakhanirons** [comment]
then close it you idiot
